# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Validate pull requests to master and dev branches for auth module.
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
pr:
  branches:
    include:
    - dev
    - master
  paths:
    include:
      - src/Authentication/Authentication/*
trigger: none
variables:
  MODULE_NAME: 'Authentication'
  BUILD_NUMBER: $[format('{0:yyMMddHHmm}', pipeline.startTime)]

jobs:
- job: MSGraphPSSDKValidation_Windows
  displayName: MS Graph PS SDK Auth Validation - Windows
  timeoutInMinutes: 360
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run: CredScan'
    inputs:
      toolMajorVersion: V2
      debugMode: false
  
  - task: PowerShell@2
    displayName: 'Generate and Build: Auth Module'
    inputs:
      filePath: '$(System.DefaultWorkingDirectory)/tools/GenerateAuthenticationModule.ps1'
      arguments: '-ModulePreviewNumber $(BUILD_NUMBER) -Build'
      pwsh: true

  - task: DotNetCoreCLI@2
    displayName: 'Run: Enabled Tests'
    inputs:
      command: 'test'
      projects: '$(System.DefaultWorkingDirectory)/src/Authentication/Authentication.Test/*.csproj'
      testRunTitle: 'Run Enabled Tests'
  
  - task: PowerShell@2
    displayName: 'Pack: Auth Module'
    inputs:
      targetType: 'inline'
      script: |
        & $(System.DefaultWorkingDirectory)/tools/PackModule.ps1 -Module $(MODULE_NAME) -ArtifactsLocation $(Build.ArtifactStagingDirectory)
      pwsh: true
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Auth Module'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop
  
  - task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
    displayName: 'Graph Client Tooling pipeline fail notification'
    inputs:
      addressType: serviceEndpoint
      serviceEndpointName: 'microsoftgraph pipeline status'
      title: '$(Build.DefinitionName) failure notification'
      text: 'This pipeline has failed. View the build details for further information. This is a blocking failure. '
    condition: and(failed(), ne(variables['Build.Reason'], 'Manual'))
    enabled: true

- job: MSGraphPSSDKValidation_Linux
  displayName: MS Graph PS SDK Auth Validation - Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Run: Enabled Tests'
    inputs:
      command: 'test'
      projects: '$(System.DefaultWorkingDirectory)/src/Authentication/Authentication.Test/*.csproj'
      testRunTitle: 'Run Enabled Tests'

  - task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
    displayName: 'Graph Client Tooling pipeline fail notification'
    inputs:
      addressType: serviceEndpoint
      serviceEndpointName: 'microsoftgraph pipeline status'
      title: '$(Build.DefinitionName) failure notification'
      text: 'This pipeline has failed. View the build details for further information. This is a blocking failure. '
    condition: and(failed(), ne(variables['Build.Reason'], 'Manual'))
    enabled: true
  
- job: MSGraphPSSDKValidation_MacOS
  displayName: MS Graph PS SDK Auth Validation - MacOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Run: Enabled Tests'
    inputs:
      command: 'test'
      projects: '$(System.DefaultWorkingDirectory)/src/Authentication/Authentication.Test/*.csproj'
      testRunTitle: 'Run Enabled Tests'

  - task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
    displayName: 'Graph Client Tooling pipeline fail notification'
    inputs:
      addressType: serviceEndpoint
      serviceEndpointName: 'microsoftgraph pipeline status'
      title: '$(Build.DefinitionName) failure notification'
      text: 'This pipeline has failed. View the build details for further information. This is a blocking failure. '
    condition: and(failed(), ne(variables['Build.Reason'], 'Manual'))
    enabled: true